name: Daily Oil Price Notify

on:
  schedule:
    - cron: "0 1 * * *" # UTC 時間每天 1:00 執行（台灣是 UTC+8，請調整時差）
  workflow_dispatch: # 可手動觸發

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # 指定 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run oil price bot
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        run: |
          python py.py
